### ISSUE TITLE
vty-5.20 build failure with microlens-0.4.9

### ISSUE THREAD

**Issue by DanBurton** [jtdaugherty/vty#147] opened 2018-03-09 22:14 UTC
Build failure as seen on the Stackage build server:

```
Building library for vty-5.20..
[21 of 36] Compiling Graphics.Vty.Input.Loop ( src/Graphics/Vty/Input/Loop.hs, .stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/Graphics/Vty/Input/Loop.o )

/Users/dan/scratch/vty-5.20/src/Graphics/Vty/Input/Loop.hs:226:21: error:
    Ambiguous occurrence ‘<>~’
    It could refer to either ‘Lens.Micro.<>~’,
                             imported from ‘Lens.Micro’ at src/Graphics/Vty/Input/Loop.hs:27:1-17
                          or ‘Graphics.Vty.Input.Loop.<>~’,
                             defined at src/Graphics/Vty/Input/Loop.hs:229:3
    |
226 | l <>= a = modify (l <>~ a)
    |                     ^^^
```

I was able to reproduce this error locally like so:

```bash
stack unpack vty-5.20 && cd vty-5.20
edit stack.yaml #add the following stack.yaml
stack build
```

```yaml
# stack.yaml
resolver: nightly-2018-03-07
extra-deps:
- microlens-0.4.9
```

**Comment by jtdaugherty** [comment] 2018-03-09 22:26
This is a duplicate of the (fixed) issue #146. Thanks!

**Closed as completed by jtdaugherty** 2018-03-09 22:26 UTC

**Comment by glguy** [comment] 2018-03-09 23:13
There are a bunch of versions of vty on hackage now that don't build because they didn't have upper bounds in place on microlens, it's worth keeping this ticket open until that's fixed. I've asked @hvr about rerunning https://matrix.hackage.haskell.org/package/vty 

Keep in mind that having these old versions around now will poison the solver, so it's not enough to just release a new version.

**Comment by jtdaugherty** [comment] 2018-03-09 23:25
It looks like Vty defined that operator itself starting in `5.5.0`, when I ported it from `lens` to `microlens`. So all versions going back that far need to have their metadata updated. Thanks, @glguy!

**Comment by jtdaugherty** [comment] 2018-03-09 23:39
I've updated the metadata for all versions starting with `5.5.0`.
