### ISSUE TITLE
Test suite build failure (due to GHC 8.2 perhaps)

### ISSUE THREAD

**Issue by snoyberg** [jtdaugherty/vty#132] opened 2017-07-31 07:04 UTC
```
[4 of 4] Compiling VerifyParseTerminfoCaps ( test/VerifyParseTerminfoCaps.hs, dist/build/verify-parse-terminfo-caps/VerifyParseTerminfoCaps.o )

test/VerifyParseTerminfoCaps.hs:39:61: warning: [-Wdeprecations]
    In the use of ‘tiGetStr’
    (imported from System.Console.Terminfo, but defined in System.Console.Terminfo.Base):
    Deprecated: "use tiGetOutput instead."
   |
39 | fromCapname ti name = fromJust $ Terminfo.getCapability ti (Terminfo.tiGetStr name)
   |                                                             ^^^^^^^^^^^^^^^^^

test/VerifyParseTerminfoCaps.hs:49:66: warning: [-Wdeprecations]
    In the use of ‘tiGetStr’
    (imported from System.Console.Terminfo, but defined in System.Console.Terminfo.Base):
    Deprecated: "use tiGetOutput instead."
   |
49 |                         return $ case Terminfo.getCapability ti (Terminfo.tiGetStr capName) of
   |                                                                  ^^^^^^^^^^^^^^^^^

<no location info>: error: module ‘Verify’ cannot be found locally

<no location info>: error:
    module ‘Verify.Data.Terminfo.Parse’ cannot be found locally

<no location info>: error:
    module ‘Verify.Graphics.Vty.Output’ cannot be found locally
```

**Comment by jtdaugherty** [comment] 2017-08-01 02:37
Thanks for the report!

Interestingly, on Vty 5.16, GHC 8.2.1, and `cabal-install` 1.24.0.2, I do not see the above build failure with `cabal new-build --enable-tests`. I see the deprecation warnings, but none of the `cannot be found locally` errors.

**Comment by glguy** [comment] 2017-08-01 03:04
It seems that the problem is related to Cabal-2. I get the test build failures on GHC 8.0.2 with new Cabal. In particular I suspect that the detailed-0.9 test type isn't working correctly in new Cabal

**Comment by jtdaugherty** [comment] 2017-08-04 05:46
On the assumption that @glguy is right and this is related to Cabal 2, I'm going to close this since there isn't much I can do (and the original output strongly suggests Cabal is definitely broken there). If that turns out to be wrong, we can revisit. Thanks!

**Closed as completed by jtdaugherty** 2017-08-04 05:46 UTC
