### ISSUE TITLE
5.18.1 prints escape sequences

### ISSUE THREAD

**Issue by int-index** [jtdaugherty/vty#137] opened 2017-12-02 11:51 UTC
Bug observed with the following terminal emulators:

```
$ xfce4-terminal --version
xfce4-terminal 0.6.3 (Xfce 4.12)

$ gnome-terminal --version
GNOME Terminal 3.18.3
```

My app on `vty-5.18`:

![image](https://user-images.githubusercontent.com/4061728/33515130-0ffa2928-d770-11e7-82ec-b4500cc9925f.png)

My app on `vty-5.18.1`:

![image](https://user-images.githubusercontent.com/4061728/33515101-aad32540-d76f-11e7-8bbd-ffe365981558.png)

It works fine with XTerm(322).

**Comment by jtdaugherty** [comment] 2017-12-02 17:20
What is `TERM` in both of those cases?

**Comment by jtdaugherty** [comment] 2017-12-02 17:25
Oh, the problem is that Vty is emitting close hyperlink escapes (the right behavior) but that is only supported in Gnome Terminal starting at version 3.26. I don't know which version of xfce4-terminal supports it, but it's at least listed here: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

I'll look into a way to deal with this.

**Comment by jtdaugherty** [comment] 2017-12-02 18:40
Perhaps the biggest obstacles to fixing this are:
* Terminfo databases tend not to mention this feature because it is new (and beyond that, terminfo tends to be stale with respect to other features, even ones that *aren't* new). I would be shocked if this even makes it into terminfo ever.
* Moving this functionality into the Xterm-specific backend in Vty wouldn't even avoid this problem, because many terminals (such as `gnome-terminal`) tend to set `TERM` to an `xterm` variant, and Vty uses `TERM` to determine some behaviors. So even if Vty used the `TERM` value to drive this instead of terminfo, it'd still emit sequences on the terminals you mentioned above.
* This feature was designed specifically to behave well on terminals that don't support it: ostensibly the unsupported sequences would just be silently ignored. Apparently in the versions of those terminals you mentioned, that isn't the case.

**Comment by jtdaugherty** [comment] 2017-12-02 18:42
From https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda:

> ... almost all terminal emulators ignore the OSC sequences they don't know about, so emitting OSC 8 will result in the anchor text not becoming a hyperlink, and the target URI getting lost.  (Unfortunately VTE prior to 0.48.2 is an exception, it prints the URI plus some garbage too.)

Can you find out which version of VTE your `gnome-terminal` is using?

**Comment by jtdaugherty** [comment] 2017-12-02 18:51
In the mean time I'm going to work on a patch to make this optional (and default to disabled), similar to other modes (mouse, bracketed paste, etc.).

**Comment by int-index** [comment] 2017-12-02 19:06
> What is `TERM` in both of those cases?

`TERM=xterm-256color`

> Oh, the problem is that Vty is emitting close hyperlink escapes (the right behavior) but that is only supported in Gnome Terminal starting at version 3.26. 

Sorry I didn't mention this in the report, I thought it was evident since it's the only change between 5.18 and 5.18.1.

> Can you find out which version of VTE your gnome-terminal is using?

I'm not sure what's the right way to find this out. but I opened the GitHub repo of `gnome-terminal` (https://github.com/GNOME/gnome-terminal), selected branch called `gnome-3-18`, and in `configure.ac` I found `VTE_REQUIRED=0.42.1`.

> This feature was designed specifically to behave well on terminals that don't support it

I am not sure why there's a need to emit escape sequences to close a URL when there are no escape sequences to open a URL. Why is it emitted excessively?

**Comment by jtdaugherty** [comment] 2017-12-02 19:06
(FYI, more context for xfce4-terminal can be found at https://bugzilla.xfce.org/show_bug.cgi?id=13534)

**Comment by jtdaugherty** [comment] 2017-12-02 19:20
> I am not sure why there's a need to emit escape sequences to close a URL when there are no escape sequences to open a URL. Why is it emitted excessively?

Because otherwise the alternative is to track whether a URL was emitted and emit the close sequence conditionally. The same thing is done with color reset sequences: they are emitted at the end of every line to prevent color over-runs from one line to the next, which is also necessary with URL sequences.

**Comment by int-index** [comment] 2017-12-02 20:03
> Because otherwise the alternative is to track whether a URL was emitted and emit the close sequence conditionally. The same thing is done with color reset sequences

I see, for some reason I assumed that it's how it worked with color sequences (emitting conditionally).

**Comment by jtdaugherty** [comment] 2017-12-02 22:41
A fix is now ready on a branch: https://github.com/jtdaugherty/vty/tree/feature/optional-hyperlinking

Can you give it a try? (No changes to your program are necessary, since the new functionality just turns off hyperlinking by default.)

**Comment by jtdaugherty** [comment] 2017-12-02 22:43
(Also, @aisamanra, if you have time, please see the patch on the aforementioned branch so you're aware.)

**Comment by jtdaugherty** [comment] 2017-12-02 22:44
(@aisamanra - when this gets merged I will also update `matterhorn` to enable hyperlinking mode.)

**Comment by int-index** [comment] 2017-12-03 06:30
Tested with `d3235b1`, the issue is solved. @jtdaugherty

**Comment by jtdaugherty** [comment] 2017-12-03 06:36
The fix is now merged and released in `5.19`. Thanks for reporting this!

**Closed as completed** 2017-12-03 06:36 UTC

**Comment by egmontkob** [comment] 2017-12-03 15:42
Just for future reference:

The simplest way to figure out VTE's version is `echo $VTE_VERSION` (e.g. the value `4801` means VTE 0.48.1, etc.). This, however, produces misleading output if you start a new enough VTE-based emulator, and from that you start one based on an older VTE (which didn't set this environment variable) or start a totally different terminal emulator; since obviosuly VTE_VERSION remains set in these cases.

The most robust way of figuring out is to execute `echo -ne '\e[>c'`, this will inject a few keypresses (as if you typed from the keyboard), including the version number in the aforementioned 4-digit format.

**Comment by jtdaugherty** [comment] 2017-12-03 16:45
Thanks, @egmontkob!
