### ISSUE TITLE
Support setting cursor style to vertical bar

### ISSUE THREAD

**Issue by sullyj3** [jtdaugherty/vty#221] opened 2021-04-20 01:47 UTC
Some terminals support escape sequences for switching the cursor from a block to a vertical bar. It would be handy to support this!

**Comment by jtdaugherty** [comment] 2021-04-20 15:42
Do you happen to know any details about how this is supported? In order to consider adding this to Vty, I need to understand how widespread support for this is, and I'll also need to know whether it's detectable (e.g. in `terminfo`) and how it behaves in terminals that don't support it.

**Comment by jtdaugherty** [comment] 2024-02-14 22:13
I realized this is a duplicate of #243, essentially, so I'm going to close it.

**Closed as completed by jtdaugherty** 2024-02-14 22:13 UTC
